config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [ :new, :create ]
  end
  resources :reviews, only: [ :index ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5] }
  validates :rating, numericality: { only_integer: true }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :find_restaurant, only: [ :show, :edit, :update, :destroy ]

  def index
    @restaurants = Restaurant.all
  end

  def show
    @reviews = Review.where(restaurant_id: params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
     if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @restaurant.update(restaurant_params)
      @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :edit
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_restaurant, only: [:new, :create]

  def index
    @reviews = Review.all
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = Restaurant.find(params[:restaurant_id])
    @review.save
    redirect_to restaurant_path(@restaurant)
  end

  private

  def find_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fa fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <%=  image_tag("yelp.png") %>
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <a href="" class="navbar-wagon-item navbar-wagon-link">Host</a>
    <a href="" class="navbar-wagon-item navbar-wagon-link">Trips</a>
    <a href="" class="navbar-wagon-item navbar-wagon-link">Messages</a>

    <!-- Profile picture with dropdown list -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <img src="http://www.cutcodedown.com/images/burgerIcon.png" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Profile</a></li>
          <li><a href="#">Dashboard</a></li>
          <li><a href="#">Log Out</a></li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Host</a></li>
        <li><a href="#">Trips</a></li>
        <li><a href="#">Messagese</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
  </head>

  <body>
    <%= render :partial => 'layouts/navbar' %>
     <div class="container">
        <div class="row">
          <div class="col-sm-offset-2 col-sm-8">
            <%= yield %>
          </div>
        </div>
      </div>
    <%= render :partial => 'layouts/footer' %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(restaurant) do |f| %>
  <% if restaurant.errors.any? %>
    <div class="errors-container">
      <ul>
        <% restaurant.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :category %>
    <%= f.select :category, ["chinese", "italian", "japanese", "french", "belgian"] %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Feel free to edit your restaurant <%= @restaurant.name %> here </h1>

<%= render 'form', restaurant: @restaurant %>
<%= link_to("Back", restaurants_path) %>

app/views/restaurants/index.html.erb
<h1>My list of restaurants</h1>

<% i = 0 %>
<% @restaurants.each do |restaurant| %>
  <% i += 1 %>
  <% if i == 10 %>
    <% break %>
  <% else %>
    <div class="card">
      <div class="text">
        <h2><%=restaurant.name %></h2>
        <p><strong>Adress: </strong><%=restaurant.address %></p>
        <p><strong>Phone: </strong><%=restaurant.phone_number %></p>
        <p><strong>Category: </strong><%=restaurant.category %></p>
      </div>
      <div class="btns">
        <div class="my-btn">
          <i class="fas fa-search btn-icn"></i><%= link_to("Show", restaurant_path(restaurant), class: "btn-fnt") %>
        </div>
        <div class="my-btn">
          <i class="far fa-edit btn-icn"></i><%= link_to("Edit", edit_restaurant_path(restaurant), class: "btn-fnt") %>
        </div>
        <div class="my-btn">
          <i class="far fa-trash-alt btn-icn"></i> <%= link_to("Delete", restaurant_path(restaurant), method: :delete, data: { confirm: "Are you sure?" }, class: "btn-fnt") %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/restaurants/new.html.erb
<h1>Please add a new restaurant here: </h1>
<%= render 'form', restaurant: @restaurant %>
<%= link_to("Back", restaurants_path) %>

app/views/restaurants/show.html.erb
<h1>Your Restaurant Selection is: <%= @restaurant.name %></h1>
<h2><%= @restaurant.name %></h2>
<p><%= @restaurant.address %></p>

<% @reviews.each do |review| %>
  <h2><%= review.content %></h2>
  <p><%= review.rating %></p>

<% end %>
<%= link_to("Add review", new_restaurant_review_path(@restaurant)) %>
<%= link_to("Back", restaurants_path) %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/index.html.erb
<h1>My list of reviews</h1>
<% @reviews.each do |review| %>
  <h2><%= review.content %></h2>
  <p><%= review.rating %></p>
<% end %>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "add a review", class: "btn btn-primary" %>
<% end %>